MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning_web/router.ex
defmodule SupinfoPhoenixLearningWeb.Router do
  use SupinfoPhoenixLearningWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json", "html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", SupinfoPhoenixLearningWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/alive", PageController, :alive
  end

  scope "/hello", SupinfoPhoenixLearningWeb do
    pipe_through :browser

    get "/", HelloController, :index
    get "/polite/:nom/:sexe", HelloController, :polite_messenger
  end

  scope "/api", SupinfoPhoenixLearningWeb do
    pipe_through :api

    get "/healthy", ApiController, :healthy
    get "/", ApiController, :get_test
    post "/", ApiController, :post_test
    put "/", ApiController, :put_test
    delete "/", ApiController, :delete_test

    # Ressources path for books
    resources "/books", BookController
  end
end

MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning/models/books.ex
defmodule SupinfoPhoenixLearning.SupinfoPhoenixLearningWeb.Books do
  use Ecto.Schema
  import Ecto.Changeset
  alias SupinfoPhoenixLearning.SupinfoPhoenixLearningWeb.Books
  alias SupinfoPhoenixLearning.Repo
  require Logger

  @derive {Poison.Encoder, only: [:author, :bookId, :title, :editor, :publicationDate]}


  schema "books" do
    field :author, :string
    field :bookID, :string
    field :editor, :string
    field :publicationDate, :utc_datetime
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(%Books{} = books, attrs \\ %{}) do
    books
    |> cast(attrs, [:bookID, :title, :author, :editor, :publicationDate])
    |> validate_required([:bookID, :title, :author])
    |> unique_constraint(:bookID)
  end

  def changeset_update(%Books{} = books, attrs \\ %{}) do
    books
    |> cast(attrs, [:title, :author, :editor, :publicationDate])
  end

  defp get_pub_date(%{"publication-date" => date}) do
    date
  end

  defp get_pub_date(%{"publicationDate" => date}) do
    date
  end

  defp get_id(%{"book-id" => id}), do: id 

  defp get_id(%{"bookID" => id}), do: id  

  def parse(book) do
    date = get_pub_date(book)
    pub_date = Ecto.DateTime.cast date
    pub_date =
      unless elem(pub_date, 0) == :ok do
        nil 
      else
        elem(pub_date, 1)
      end

    %Books{
      bookID: get_id(book),
      title: book["title"],
      author: book["author"],
      editor: book["editor"],
      publicationDate: pub_date
    }
  end

  def update(old, new) do
    old
    |> changeset_update(new)
    |> Repo.update()
  end
end

MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning_web/controllers/book_controller.ex
defmodule SupinfoPhoenixLearningWeb.BookController do
  use SupinfoPhoenixLearningWeb, :controller
  alias SupinfoPhoenixLearning.Repo
  alias SupinfoPhoenixLearning.SupinfoPhoenixLearningWeb.Books
  require Logger
  import Ecto.Query

  def index(conn, _par) do
    json conn, Repo.all(Books)
  end

  def edit(conn, %{"id" => id}) do
    Logger.debug "Edit ????"
    current_book = Repo.one(from b in Books, where: ilike(b.bookID, ^id))
    render conn, "edit.html", changeset: Books.changeset(%Books{}), old_book: current_book
  end

  def new(conn, _par) do
    render conn, "new.html", changeset: Books.changeset(%Books{})
  end

  def show(conn, %{"id" => id}) do
    json conn, Repo.one(from b in Books, where: ilike(b.bookID, ^id))
  end

  def create(conn, book) do
    ins_book = 
      if Map.has_key?(book, "book") do
        Books.parse book["book"]
      else
        Books.parse book
      end
    try do
      Repo.insert(ins_book)
      json conn, %{ok: "Well created book.", book: ins_book}
    rescue
      _ ->
        conn = conn.put_status 422
        json conn, %{ok: "Error while creating book.", book: ins_book}
    end
  end

  def update(conn, %{"id" => id, "book" => book}) do
    current_book = Repo.one(from b in Books, where: ilike(b.bookID, ^id))
    ins_book = 
      if Map.has_key?(book, "book") do
        book["book"]
      else
        book
      end
    res = Books.update(current_book, ins_book)
    unless elem(res, 0) == :ok do
      json conn, %{ok: "Error while updating book.", error: elem(res, 1), new_book: book}
    else
      json conn, %{ok: "Well updated book.", new_book: book}
    end
  end

  def delete(conn,  %{"id" => id}) do
    book = Repo.one(from b in Books, where: ilike(b.bookID, ^id))
    res = Repo.delete(book)
    unless elem(res, 0) == :ok do
      json conn, %{ok: "Error while deleting book.", error: elem(res, 1), book: book}
    else
      json conn, %{ok: "Well deleted book.", book: book}
    end
  end
end

MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning_web/views/book_view.ex
defmodule SupinfoPhoenixLearningWeb.BookView do
  use SupinfoPhoenixLearningWeb, :view
end

MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning_web/templates/book/edit.html.eex
<div class="jumbotron">
  <h2>Edit Book</h2>
  <%= form_for @changeset, book_path(@conn, :update, @old_book.bookID), [as: :book, method: :put], fn f -> %>
    <label>
       Title: <%= text_input f, :title, value: @old_book.title %>
    </label>
    <label>
        Author: <%= text_input f, :author, value: @old_book.author %>
    </label>
    <label>
        Editor: <%= text_input f, :editor, value: @old_book.editor %>
    </label>
    <label>
        Publication date: <%= datetime_select f, :publicationDate, value: @old_book.publicationDate %>
    </label>
    <%= submit "Update" %>
  <% end %>
</div>

MSc1/elixir_article/phoenix_framework/supinfo_phoenix_learning/lib/supinfo_phoenix_learning_web/templates/book/new.html.eex
<div class="jumbotron">
  <h2>New Book</h2>
  <%= form_for @changeset, book_path(@conn, :create), [as: :register], fn f -> %>
    <label>
       Title: <%= text_input f, :title %>
    </label>
    <label>
        Author: <%= text_input f, :author %>
    </label>
    <label>
        Editor: <%= text_input f, :editor %>
    </label>
    <label>
        Book id: <%= text_input f, :bookID %>
    </label>
    <label>
        Publication date: <%= datetime_select f, :publicationDate %>
    </label>
    <%= submit "Register" %>
  <% end %>
</div>